services:
  frontend:
    image: pw14a:latest
    volumes:
      - dbdata:/prj/pw14a/src/
volumes:
  dbdata:
    name: ${PEGASO_DATABASE_URL}
    labels:
      descrizione: "Database del progetto PW14A"
      tipo: "SQLITE"