services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docker/volumes/media:/app/src/media                            # Volume per i media files
    environment:
      - DJANGO_SETTINGS_MODULE=albdif.config.settings
      - PEGASUS_MEDIA_ROOT=/var/app/media/
      - PEGASUS_MEDIA_URL=${PEGASUS_MEDIA_URL}
      - PEGASUS_STATIC_ROOT=${PEGASUS_STATIC_ROOT}
      - PEGASUS_DATABASE_URL=postgres://user:password@postgres:5432/prj14a
      - PEGASUS_SOCIAL_AUTH_REDIRECT_IS_HTTPS=False
      - PEGASUS_SOCIAL_AUTH_GITHUB_KEY=${PEGASUS_SOCIAL_AUTH_GITHUB_KEY}
      - PEGASUS_SOCIAL_AUTH_GITHUB_SECRET=${PEGASUS_SOCIAL_AUTH_GITHUB_SECRET}
      - PEGASUS_SOCIAL_AUTH_GITHUB_REDIRECT_URI=${PEGASUS_SOCIAL_AUTH_GITHUB_REDIRECT_URI}
    command: >
       sh -c "python src/manage.py migrate && 
              python src/manage.py crea_dati_test &&
              python src/manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      - POSTGRES_DB=prj14a
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge