# Generated by Django 4.2.17 on 2025-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0002_alter_prezzocamera_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='data_stato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitatore',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato_prenotazione',
            field=models.CharField(choices=[('PR', 'Registrata'), ('PG', 'Confermata e Pagata'), ('CA', 'Cancellata'), ('RR', 'Richiesta Rimborso'), ('RE', 'Rimborsata'), ('NE', 'Negata'), ('SC', 'Scaduta')], default='PR', max_length=2),
        ),
    ]
