# Generated by Django 5.1.3 on 2024-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0002_alter_calendarioprenotazione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprieta',
            name='principale',
            field=models.BooleanField(default=False, help_text="Indica se è l'AD principale"),
        ),
    ]
