# Generated by Django 4.2.17 on 2025-01-18 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albdif', '0003_prenotazione_data_stato_visitatore_partita_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaAdesione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richiesta_adesione', models.FileField(upload_to='adesioni')),
                ('data_richiesta', models.DateTimeField(default=datetime.datetime.now)),
                ('approvazione_adesione', models.FileField(blank=True, null=True, upload_to='approvazioni')),
                ('data_adesione', models.DateTimeField(blank=True, null=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta adesione',
                'verbose_name_plural': 'Richieste adesioni',
            },
        ),
    ]
