# Generated by Django 4.2.17 on 2025-01-05 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0008_prenotazione_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='contratto',
            field=models.FileField(blank=True, null=True, upload_to='contratti_host'),
        ),
        migrations.AddField(
            model_name='host',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitatore',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='visitatore',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='version',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 10, 51, 38, 245573)),
        ),
    ]
