# Generated by Django 4.2.17 on 2025-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0009_host_codice_fiscale_host_contratto_host_partita_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='version',
        ),
        migrations.AddField(
            model_name='proprieta',
            name='nome',
            field=models.CharField(default='... inserire un nickname', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato_prenotazione',
            field=models.CharField(choices=[('PR', 'Registrata'), ('PG', 'Confermata'), ('CA', 'Cancellata'), ('RR', 'Richiesta Rimborso'), ('RE', 'Rimborsata'), ('NE', 'Negata'), ('SC', 'Scaduta')], default='PR', max_length=2),
        ),
    ]
