# Generated by Django 4.2.17 on 2025-01-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0010_remove_prenotazione_version_proprieta_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='richiesta_associazione',
            field=models.FileField(blank=True, null=True, upload_to='richiesta_host'),
        ),
        migrations.AlterField(
            model_name='stagione',
            name='stagione',
            field=models.CharField(choices=[('Bassa', 'Bassa stagione'), ('Media', 'Media stagione'), ('Alta', 'Alta stagione')], max_length=50),
        ),
    ]
